kind: pipeline
name: default
type: docker

steps:
  - name: docker master
    image: plugins/docker
    settings:
      repo: CuriousIbrahim/nginx-le
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tags:
        - ${DRONE_COMMIT_BRANCH/\//-}
    when:
      branch: [master]
      event: push
